# UNIT I

## MODULE 2
## TOPIC : Numpy 

Question 1

Write a function that takes a one-dimensional numpy array as input and returns the running sum of the array.

Input Format
    
    First line of input consist of the values entered in the 1D array
Output Format
    
    Returns the running sum of array
Sample Input 1
    
    1 2 3 4 5
Sample Output 1
    
    [ 1  3  6 10 15]

In [ ]:
import numpy as np

def running_sum(arr):
    return np.cumsum(arr)

lis = list(map(int,input().strip().split()))    
original_array = np.array(lis)
print(running_sum(original_array))


Question 2

1D array of marks scored by JEE students are taken in calculation. Find the marks which are of 0th percentile, 25th percentile, 50th percentile, 75th percentile, 100th percentile
    
Input Format
    
    First line consist of number of elements
    
    Second line consist of marks stored in array
    
Output Format 
    
    first line print the array
    
    second line 0th percentile
    
    third line 25th percentile 
    
    fourth line 50th percentile 
    
    fifth line 75th percentile
    
    last line 100th percentile
    
Sample input
    
    5
    34 54 56 87 32
    
Sample output
    
    [34. 54. 56. 87. 32.]
    0th percentile of a :  32.0
    25th percentile of a :  34.0
    50th percentile of a :  54.0
    75th percentile of a :  56.0
    100th percentile of a :  87.0

In [ ]:
import numpy as np

n = int(input()) # get the number of elements in a list
  
a = np.array(list(map(float,input().strip().split()))[:n])  
# 1D aay

print( a)
print("0th percentile of a : ",
       np.percentile(a, 0))
print("25th percentile of a : ",
       np.percentile(a, 25))
print("50th percentile of a : ",
       np.percentile(a, 50))
print("75th percentile of a : ",
       np.percentile(a, 75))
print("100th percentile of a : ",
       np.percentile(a, 100))

#### Question 3

Write a function that takes a one-dimensional numpy array as input and returns the indices of the array where the element is greater than the average of all the elements.

Input Format
    
    First line consist of the 1D array from user
Output Format

    Returns the indices array of elements which are greater than the avg of all elements
Sample Input 1

    1 2 4 5 6 7 8 9 10 
Sample Output 1

    (array([4, 5, 6, 7, 8]),)

In [ ]:
import numpy as np

def find_above_average(arr):
    average = np.mean(arr)
    above_average_indices = np.where(arr > average)
    return above_average_indices

original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(find_above_average(original_array))


#### Question 4

Write a function that take 2 dimensional array and return the transpose of the array after flattening the array

Input Format
    
    First line consist of the number of rows

    Second line consist of the number of columns

    Finally enter the values for the matrices

Output Format
    
    Returns the Final transpose matrix after flattening.
Sample Input 1
    
    2
    2 
    1
    2
    3
    4
Sample Output 1

    [1 2 3 4]
Sample Input 2

    3
    3
    1
    2
    3
    4
    5
    6
    7
    8
    9
Sample Output 2
    
    [1 2 3 4 5 6 7 8 9]

In [ ]:
import numpy as np

def flatten_and_transpose(arr):
    return np.transpose(arr.ravel())

r = int(input())
c = int(input())
mat = np.array([[int(input()) for x in range (c)] for y in range(r)])

print(flatten_and_transpose(mat))

#### Question 5

Write a function that takes a one-dimensional numpy array as input and returns the indices of the array where the difference between each element and its nearest neighbor is greater than a certain threshold.

Input Format
    
    First line consist of the 1D array values from user
    Second input consist of the threshold value.
Output Format

    Output should be the outliers in a array
Sample Input 1
    
    1 2 3 4 5 10 20 30 40
    4
Sample Output 1

    [5 6 7 8]

In [ ]:
import numpy as np

def find_outliers(arr, threshold=1):
    diff = np.abs(np.diff(arr))
    outliers = np.where(diff > threshold)[0]
    return outliers + 1

lis = list(map(int,input().strip().split()))  
th = int(input())
print(find_outliers(lis, th))

#### Question 6

Write a function that takes a one-dimensional numpy array as input and returns the running sum of the array.

Input Format
    
    First line of input consist of the values entered in the 1D array
Output Format
    
    Returns the running sum of array
Sample Input 1
    
    1 2 3 4 5
Sample Output 1
    
    [ 1  3  6 10 15]

In [ ]:
import numpy as np

def running_sum(arr):
    return np.cumsum(arr)
    
original_array = np.array([1, 2, 3, 4, 5])
print(running_sum(original_array))
# output: [1 3 6 10 15]

#### Question 7

Given data create a data frame in pandas with the given data.

Datas:
    
    'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
    'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
    'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
    'Points':[876,789,863,673,741,812,756,788,694,701,804,690]

Your task is to display the data based on the year the user gives.



Input Format

    First line of the program consist of the year
Output Format
    
    Displays the data based on the year
Sample Input 1

    2015
Sample Output 1
    
        Team  Rank  Year  Points
    1   Riders     2  2015     789
    3   Devils     3  2015     673
    5    kings     4  2015     812
    10  Royals     1  2015     804

In [ ]:
import pandas as pd

cric_match = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
   'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
   'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
   'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
   'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

df = pd.DataFrame(cric_match)

grouped = df.groupby('Year')

print(grouped.get_group(2015))

#### Question 8

Get a string of 4 values separated by commas from user. Convert the string to a 2X2 matrix by creating a user defined function for it.

Create a function name converter1 which will convert the given string as a array.

Create a function name converter2 which will convert the array to a 2X2 matrix.

Similarly get 2 matrix from the user and use the matrix to do the following questions.

- Multiplication of the two matrix

- Cube of the each individual matrix

- Rank of the each individual matrix


Input Format

    First line of input consist of 4 values of string separated by commas for 1st matrix

    Second line of input consist of 4 values of string separated by commas for 2nd matrix
Output Format

    First line consist of the Dot multiplication of two matrices
    Second line consist of the rank of the matrix 1
    Third line consist of the rank of the matrix 2
    Fourth line consist of the cube of matrix 1
    Fifth line consist of the cube of matrix 2
    Sixth line consist of the multiplication of two matrices
Sample Input 1
    
    1,2,3,4
    11,12,13,14
Sample Output 1
    
    DOT MULTIPLICATION
        
        [[37 40]
         [85 92]]
   RANK OF THE MATRICES
        
        2
        2
   CUBE OF MATRICES
        
        [[ 37  54]
         [ 81 118]]
        [[6947 7524]
         [8151 8828]]
   MULTIPLICATION OF TWO MATRICES
   
         [[ 7 10]
         [15 22]]

In [ ]:
import numpy as np

def converter1(mat):
    return converter2(np.fromstring(mat,dtype= int,sep = ','))

def converter2(mat):
    return mat.reshape(2,2)

mat1 = input()
mat2= input()
new_mat1  = converter1(mat1)
new_mat2 = converter1(mat2)

print('DOT MULTIPLICATION')
print(np.dot(new_mat1,new_mat2))
print('RANK OF THE MATRICES')
print(np.linalg.matrix_rank(new_mat1))
print(np.linalg.matrix_rank(new_mat2))
print('CUBE OF MATRICES')
print(np.linalg.matrix_power(new_mat1,3))
print(np.linalg.matrix_power(new_mat2,3))
print('MULTIPLICATION OF TWO MATRICES')
print(np.matmul(new_mat1,new_mat1))

#### Question 9

Get a array as a input and add the first and the last value of both for both row and column representation.
    
Input Format
    
    First line consist of number of rows
    
    Second line consist of number of columns
    
    The following line consist of entry of the input values
    
Output Format 
    
    print the array
    
    list of added values
    
Sample input
    
    2 # no of rows
    2 # no of columns
    1
    2
    3
    4
    
Sample Output
    
    [[1 2]
    [3 4]]
    row [4 6]
    column [3 7]

In [ ]:
import numpy as np

def add(mat):
    return(mat[0]+mat[-1])

R = int(input())
C = int(input())
mat = np.array([[int(input()) for x in range (C)] for y in range(R)])
print(mat)
print('row',np.apply_along_axis(add,0,mat))
print ('column',np.apply_along_axis(add,1,mat))

#### Question 10

Get a array as a input and check the values in the array are greater than the target value if not multiply the value by 5.
    
Input Format
    
    First line consist of target value
    
    Second line consist of number of rows
    
    Third line consist of number of columns
    
    The following line consist of entry of the input values
    
Output Format 
    
    a array of changed values
    
Sample Input
    
    5 # target value
    2 # no of rows
    2 # no of columns
    1
    56
    5
    6
    
Sample Output
    
    [[  1 280]
    [ 25  30]]

In [ ]:
import numpy as np
t = int (input())
R = int(input())
C = int(input())
mat = np.array([[int(input()) for x in range (C)] for y in range(R)])

print(np.where(mat<t,mat,mat*5))

#### Question 11

Create an random 2D array of integers from 1 to 100. Find the max along each column and each row of the array.
    
Input Format
    
    First line of the input consist of the number of rows
    
    Second line of the input consist of the number of columns
    
Output Format
    
     
    
    Display the created array
    
    Display the list of max number in the row
    
    Display the list of max number in column
    
Sample input
    
    2
    3
    
Sample output
    
    [[38  6 92]
    [13 27  4]]
    
    [92 27]
    [38 27 92]

In [ ]:
import numpy as np
n = int (input())
m = int (input())

ta = np.random.randint(1,100,(n,m))
print(ta)
mta = np.amax(ta, axis = 1)
mtac = np.amax(ta, axis = 0)

print( mta)
print( mtac)